apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navno-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /person/navno-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/navno-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/navno-api/internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: {{ meldekort-api-host }}
  ingresses:
    {{#each ingresses}}
    - {{this}}
    {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: navno-api-secret
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
